"""
attach_verses.py - generate verses.js for concordagraph.html

The graph ships with references and short summaries only. This script reads
your own verse index and writes a companion file holding the full text of
just the passages the graph uses, so your local copy of the page can show
them on click.

Why it works this way: the NRSV is under copyright. The graph is
distributable; the verse payload is not. Keeping them in separate files
means you can share or publish concordagraph.html freely while your own
copy still reads the full text. verses.js is for your machine. Do not
publish it, commit it, or send it on.

Usage
-----
    python3 attach_verses.py                     # reads ./verses.json
    python3 attach_verses.py --index path/to/verses.json
    python3 attach_verses.py --graph path/to/concordagraph.html

Put the resulting verses.js in the same folder as concordagraph.html and
open the page. It loads the file if present and ignores it if absent.
"""
import argparse, json, os, re, sys

ap = argparse.ArgumentParser()
ap.add_argument('--index', default='verses.json')
ap.add_argument('--graph', default='concordagraph.html')
ap.add_argument('--out',   default='verses.js')
args = ap.parse_args()

for p in (args.index, args.graph):
    if not os.path.exists(p):
        sys.exit(f'not found: {p}\nRun nrsv_index.py first, or pass --index / --graph.')

index = {r['ref']: r['text'] for r in json.load(open(args.index))}
html = open(args.graph, encoding='utf-8').read()

# Pull the reference from each node record: ["id","Book C:V","cluster","gist"]
refs = re.findall(r'^\s*\["[a-z]+\d+","((?:[1-4] )?[A-Z][A-Za-z]+ \d+:\d+)","', html, re.M)
if not refs:
    sys.exit('no node references found in the graph file — has its format changed?')

payload, missing = {}, []
for ref in refs:
    text = index.get(ref)
    if text:
        # Strip any section heading the extractor left glued to the verse end.
        text = re.sub(r'\s{2,}', ' ', text).strip()
        payload[ref] = text
    else:
        missing.append(ref)

with open(args.out, 'w', encoding='utf-8') as f:
    f.write('// Generated by attach_verses.py from your local NRSV index.\n')
    f.write('// Copyrighted text. Local use only — do not publish or redistribute.\n')
    f.write('window.NRSV = ')
    json.dump(payload, f, ensure_ascii=False, indent=0)
    f.write(';\n')

print(f'nodes in graph : {len(refs)}')
print(f'verses written : {len(payload)}  ->  {args.out}')
if missing:
    print(f'unresolved     : {len(missing)}')
    for m in missing:
        print('   ', m)
    print('\nUnresolved references mean the index disagrees with the graph.')
    print('Check them against chapters.json before trusting the node.')
else:
    print('unresolved     : 0')
