"""
build_graph.py - regenerate the data block inside concordagraph.html.

Reads corpus_nodes.csv, corpus_edges.csv and corpus_clusters.csv, checks every
reference against your verse index, refuses to write if anything fails, then
splices the generated block between the // <corpus> and // </corpus> markers.

    python3 build_graph.py
    python3 build_graph.py --no-verify      # skip the index check

Edit the CSVs, run this, reload the page. Do not hand-edit the block
between the markers — it is overwritten.

Three module rules, settled in DESIGN.md:

1. Ids are namespaced at build time from module.json. A bare id in a CSV
   (`g1`) becomes `tithe:g1`. An id that ALREADY carries a prefix is left
   alone, which is how a cross-module edge is written. Edges pointing out of
   this module are validated and held back from the single-module page,
   because it has no node to attach them to; the master compile is where they
   land.

2. Clusters live in corpus_clusters.csv, not in this script, so a second
   module needs no edit here. The `role` column carries layout meaning: the
   one cluster marked `hub` is drawn at the centre. The renderer asks for the
   role, it does not know any cluster by name.

3. Reference is identity; everything else is module-scoped. Within a module a
   verse appears at most once — enforced below. Across modules the same verse
   may appear once per module, each with its own cluster and its own summary,
   and each node carries its module so the renderer can tell them apart.
"""
import argparse, csv, json, os, sys
from collections import Counter

ap = argparse.ArgumentParser()
ap.add_argument('--nodes', default='corpus_nodes.csv')
ap.add_argument('--edges', default='corpus_edges.csv')
ap.add_argument('--clusters', default='corpus_clusters.csv')
ap.add_argument('--motifs',   default='corpus_motifs.csv')
ap.add_argument('--module', default='module.json')
ap.add_argument('--graph', default='concordagraph.html')
ap.add_argument('--index', default='verses.json')
ap.add_argument('--no-verify', action='store_true')
a = ap.parse_args()

fail, warn, notes = [], [], []

# --- the module ------------------------------------------------------------
if not os.path.exists(a.module):
    sys.exit(f'{a.module} not found. It names this module: {{"slug": "...", "title": "..."}}')
mod = json.load(open(a.module, encoding='utf-8'))
SLUG, TITLE = mod.get('slug', ''), mod.get('title', '')
if not SLUG:
    sys.exit(f'{a.module}: no "slug".')
if ':' in SLUG:
    sys.exit(f'{a.module}: slug {SLUG!r} must not contain a colon — it is the namespace separator.')

def qualify(i):
    """Bare ids get this module's prefix. Already-qualified ids pass through."""
    i = i.strip()
    return i if ':' in i else f'{SLUG}:{i}'

# --- clusters: name, colours and layout role, per module -------------------
if not os.path.exists(a.clusters):
    sys.exit(f'{a.clusters} not found. Columns: key,name,light,dark,role')
CLUSTERS = []
for row in csv.DictReader(open(a.clusters, encoding='utf-8')):
    CLUSTERS.append((row['key'].strip(), row['name'], row['light'].strip(),
                     row['dark'].strip(), (row.get('role') or '').strip(),
                     (row.get('note') or '').strip()))
for k, name, lt, dk, role, note in CLUSTERS:
    if role not in ('', 'hub'):
        fail.append(f'cluster {k}: unknown role {role!r} — use "hub" or leave it blank')
hubs = [k for k, _, _, _, role, _n in CLUSTERS if role == 'hub']
nonote = [k for k, _, _, _, _, note in CLUSTERS if not note]
if nonote:
    notes.append('cluster(s) with no note, so the page can name them but not\n'
                 '   explain them: ' + ', '.join(nonote))
if len(hubs) > 1:
    fail.append(f'more than one cluster marked hub: {", ".join(hubs)}')
dupcl = [k for k, c in Counter(k for k, *_ in CLUSTERS).items() if c > 1]
for k in dupcl:
    fail.append(f'duplicate cluster key: {k}')

# --- motifs: a SECOND axis, generated, optional -----------------------------
# A node sits in exactly one cluster, because a cluster is a topic. A node
# carries as many motifs as it has words, because a motif is a lemma and cuts
# across topics by construction - argyrion runs through four clusters, denarion
# through three. Filing either as a cluster would mean pulling verses out of
# the topic they belong to, so motifs get their own table and their own filter.
#
# corpus_motifs.csv is GENERATED by build_motifs.py from strongs_index.json.
# Do not hand-edit it; edit the MOTIFS list in that script. It is optional: a
# checkout without the lemma index still builds, just without the fourth filter.
MOTIFS = []
if os.path.exists(a.motifs):
    for row in csv.DictReader(open(a.motifs, encoding='utf-8')):
        MOTIFS.append((row['key'].strip(), row['name'],
                       [i for i in row['nodes'].split() if i],
                       int(row['scope']), row.get('note', '')))
    dupmo = [k for k, c in Counter(k for k, *_ in MOTIFS).items() if c > 1]
    for k in dupmo:
        fail.append(f'duplicate motif key: {k}')

nodes = list(csv.DictReader(open(a.nodes, encoding='utf-8')))
edges = list(csv.DictReader(open(a.edges, encoding='utf-8')))
known = {c[0] for c in CLUSTERS}
idset_pre = {n['id'].strip() for n in csv.DictReader(open(a.nodes, encoding='utf-8'))}
for k, name, ids, scope, note in MOTIFS:
    for i in ids:
        if i not in idset_pre:
            fail.append(f'motif {k}: no such node {i} — rerun build_motifs.py')
    if not ids:
        fail.append(f'motif {k}: names no nodes')

for n in nodes:
    n['id'] = qualify(n['id'])
for e in edges:
    e['source'], e['target'] = qualify(e['source']), qualify(e['target'])

ids = [n['id'] for n in nodes]
for d, c in Counter(ids).items():
    if c > 1: fail.append(f'duplicate node id: {d}')
for n in nodes:
    if n['cluster'] not in known: fail.append(f"{n['id']}: unknown cluster {n['cluster']}")

# Reference is identity: one module may not cite the same verse twice, or the
# master compile cannot tell a genuine cross-module sharing from a local typo.
for r, c in Counter(n['ref'].strip() for n in nodes).items():
    if c > 1:
        who = ', '.join(n['id'] for n in nodes if n['ref'].strip() == r)
        fail.append(f'{r} is cited by {c} nodes in this module ({who}) — reference is identity')

# A cluster nobody uses still takes a legend slot and a colour. Warn, do not
# fail: staging a cluster before populating it is legitimate.
used = {n['cluster'] for n in nodes}
for k, name, *_ in CLUSTERS:
    if k not in used:
        notes.append(f'cluster {k} ({name}) is defined but no node uses it')

idset = set(ids)
is_external = set()                          # indices into edges, not copies
for i, e in enumerate(edges):
    for end in ('source', 'target'):
        v = e[end]
        if v.split(':', 1)[0] != SLUG:
            is_external.add(i)               # points out of this module
        elif v not in idset:
            fail.append(f"edge {end} missing: {v}")
    if e['kind'] not in ('lex','ref','con'): fail.append(f"bad kind: {e['kind']}")
    if e['warrant'] not in ('states','supports','spec'): fail.append(f"bad warrant: {e['warrant']}")
# One edge per pair PER KIND. Settled 25 Sept 2026 as QUESTIONS.md Q5.
#
# The key used to be the node pair alone — sorted, so undirected, and with the
# kind left out — which meant a pair could hold exactly one edge. A finding
# that two passages BOTH share wording and make the same argument could not be
# recorded; one of the two had to be dropped into the other's note. That was
# costing a real edge: Matthew 9:9 to Mark 2:14 carried a `lex`/`states` claim
# about the shared call narrative and a `con`/`spec` claim about whether Levi
# and Matthew are one man, crammed into one note.
#
# Adding the kind lets a pair carry up to three edges, one of each kind, and
# still refuses a genuine duplicate — two `con` edges between the same pair
# would be a contradiction, not a finding, since they would assert the same
# relation at two warrants. The renderer needed no change: assignLanes lifts
# each arc until it clears every arc it overlaps, so two edges with identical
# endpoints are drawn as two stacked arcs.
seen = set()
for e in edges:
    k = tuple(sorted((e['source'], e['target']))) + (e['kind'],)
    if k in seen: fail.append(f'duplicate {k[2]} edge: {k[0]}–{k[1]}')
    seen.add(k)
external = [e for i, e in enumerate(edges) if i in is_external]
local = [e for i, e in enumerate(edges) if i not in is_external]

if not a.no_verify:
    if not os.path.exists(a.index):
        sys.exit(f'{a.index} not found. Run nrsv_index.py, or pass --no-verify.')
    raw = {r['ref']: r['text'] for r in json.load(open(a.index))}
    index = set(raw)
    for n in nodes:
        if n['ref'] not in index:
            fail.append(f"{n['id']}: {n['ref']} does not resolve in the index")

    # A resolvable reference is not a correct one. This catches the case where a
    # summary describes a different verse than the one it cites: no content word
    # in common between the summary and the verse. It WARNS rather than fails,
    # because meta-summaries ("Mark's form of the ruling") legitimately share no
    # vocabulary with the text. Read the list; do not ignore it.
    import re as _re
    STOP = set("""the and for with that this from they them their there then than have has
    had was were will would shall should could been being into onto upon what which who whom
    whose when where while because before after over under again more most other some such
    only own same both each all any are but not you your his her its our out off down about
    against form account version repeated cited together""".split())
    _stem = lambda w: _re.sub(r'(ies|es|s)$', '', w)
    def _words(s):
        return {_stem(w) for w in _re.findall(r"[a-z']+", s.lower())
                if len(w) > 3 and w not in STOP}
    for n in nodes:
        t = raw.get(n['ref'])
        if t and not (_words(n['gist']) & _words(t)):
            warn.append(f"{n['id']} ({n['ref']}): summary shares no wording with the verse "
                        f"— check it names the right passage")

# The canonical order of the cited books, taken from the index itself. The index
# is built by walking the extracted text in document order, so the order a book
# first appears IS its position in this edition — nothing is supplied from
# memory. This replaces a hardcoded 18-book list in the page that the corpus had
# outgrown: the seven books it omitted scored -1 from indexOf and sorted ahead of
# Genesis with no label on the axis.
BOOKS = []
cited_books = {n['ref'].strip().rsplit(' ', 1)[0] for n in nodes}
if not a.no_verify:
    seen_books = []
    for r in json.load(open(a.index)):
        if r['book'] not in seen_books:
            seen_books.append(r['book'])
    BOOKS = [b for b in seen_books if b in cited_books]
    for b in sorted(cited_books - set(BOOKS)):
        fail.append(f'book {b} is cited but does not appear in {a.index}')

# Abbreviations for the book axis. Edit these; anything missing is abbreviated
# mechanically and reported, so a new book is never left unlabelled.
ABBR_KNOWN = {
    'Genesis': 'Gen', 'Exodus': 'Exod', 'Leviticus': 'Lev', 'Numbers': 'Num',
    'Deuteronomy': 'Deut', 'Ruth': 'Ruth', '1 Samuel': '1 Sam', 'Nehemiah': 'Neh',
    'Psalm': 'Ps', 'Ezekiel': 'Ezek', 'Amos': 'Amos', 'Zechariah': 'Zech',
    'Malachi': 'Mal', 'Matthew': 'Matt', 'Mark': 'Mark', 'Luke': 'Luke',
    'John': 'John', 'Acts': 'Acts', 'Romans': 'Rom', '1 Corinthians': '1 Cor',
    '2 Corinthians': '2 Cor', '1 Timothy': '1 Tim', 'Hebrews': 'Heb',
    'James': 'Jas', '1 Peter': '1 Pet',
}

if fail:
    print('refusing to write:', file=sys.stderr)
    for f in fail: print('  ', f, file=sys.stderr)
    sys.exit(1)

def abbrev(b):
    if b in ABBR_KNOWN:
        return ABBR_KNOWN[b]
    num, _, name = b.rpartition(' ')
    guessed = (num + ' ' if num else '') + name[:4]
    notes.append(f'book {b} has no abbreviation; using {guessed!r} — add it to '
                 f'ABBR_KNOWN in build_graph.py to choose your own')
    return guessed

j = lambda s: json.dumps(s, ensure_ascii=False)
out = ['// <corpus>  generated by build_graph.py — edit the CSVs, not this block']
out.append(f'const MOD = {j(SLUG)};')
out.append('const MODS = {')
out.append(f'  {SLUG}:{{title:{j(TITLE)}}},')
out.append('};')
# The page used to state its own size in prose, and had drifted to claiming
# eighty-nine passages in the New Testament when the corpus held 151 across 25
# books, 46 of them Old Testament. A number the page writes about itself has to
# be generated, or it is only ever right on the day somebody typed it.
out.append(f'const META = {{nodes:{len(nodes)},edges:{len(local)},'
           f'books:{len(cited_books)}}};')
out.append(f'const BOOKS = {j(BOOKS)};')
out.append('const ABBR = {')
for b in BOOKS:
    out.append(f'  {j(b)}:{j(abbrev(b))},')
out.append('};')
out.append('const CL = {')
for k, name, lt, dk, role, note in CLUSTERS:
    out.append(f'  {k}:{{name:{j(name)},light:{j(lt)},dark:{j(dk)},'
               f'role:{j(role)},note:{j(note)}}},')
out.append('};')
# The key is quoted here deliberately. The cluster table above emits {k}: bare,
# which ships a blank page for any key that is not a single lowercase word -
# that is QUESTIONS.md Q3, still open. New code should not repeat it.
out.append('const MO = {')
for k, name, ids, scope, note in MOTIFS:
    qualified = ' '.join(f'{SLUG}:{i}' if ':' not in i else i for i in ids)
    out.append(f'  {j(k)}:{{name:{j(name)},nodes:{j(qualified)},'
               f'scope:{scope},note:{j(note)}}},')
out.append('};')
out.append('const N = [')
for n in nodes:
    out.append(f"  [{j(n['id'])},{j(n['ref'])},{j(n['cluster'])},{j(n['gist'])},{j(SLUG)}],")
out.append('];')
out.append('const E = [')
for e in local:
    out.append(f"  [{j(e['source'])},{j(e['target'])},{j(e['kind'])},{j(e['warrant'])},{j(e['note'])}],")
out.append('];')
out.append('// </corpus>')
block = '\n'.join(out)

html = open(a.graph, encoding='utf-8').read()
s, t = html.find('// <corpus>'), html.find('// </corpus>')
if s < 0 or t < 0:
    sys.exit('markers // <corpus> and // </corpus> not found in the graph file.')
html = html[:s] + block + html[t + len('// </corpus>'):]
open(a.graph, 'w', encoding='utf-8').write(html)

print(f'module: {SLUG} — {TITLE}')
print(f'wrote {len(nodes)} nodes, {len(local)} edges into {a.graph}')
if external:
    print(f'{len(external)} cross-module edge(s) held back — they have no node to attach to here:')
    for e in external: print(f"   {e['source']} -> {e['target']}")
if warn:
    print(f'\n{len(warn)} node(s) to check by eye:')
    for w in warn: print('  ', w)
if notes:
    print(f'\n{len(notes)} corpus note(s):')
    for n_ in notes: print('  ', n_)
print('clusters:', ', '.join(f'{k}={v}' for k, v in
      sorted(Counter(n["cluster"] for n in nodes).items(), key=lambda x: -x[1])))
hub = hubs[0] if hubs else None
print('hub cluster:', hub if hub else '(none — nothing drawn at the centre)')
