"""
build_graph.py - regenerate the data block inside concordagraph.html.

Reads corpus_nodes.csv and corpus_edges.csv, checks every reference against
your verse index, refuses to write if anything fails, then splices the
generated block between the // <corpus> and // </corpus> markers.

    python3 build_graph.py
    python3 build_graph.py --no-verify      # skip the index check

Edit the CSVs, run this, reload the page. Do not hand-edit the block
between the markers — it is overwritten.
"""
import argparse, csv, json, os, sys
from collections import Counter

ap = argparse.ArgumentParser()
ap.add_argument('--nodes', default='corpus_nodes.csv')
ap.add_argument('--edges', default='corpus_edges.csv')
ap.add_argument('--graph', default='concordagraph.html')
ap.add_argument('--index', default='verses.json')
ap.add_argument('--no-verify', action='store_true')
a = ap.parse_args()

# name and colours for each cluster, in the order they appear in the legend
CLUSTERS = [
 ("anchor",   "Tithe statutes",           "#7C8B96", "#93A3AE"),
 ("bridge",   "The temple tax",           "#B4553C", "#D97B60"),
 ("imperial", "Imperial tax",             "#2F6B84", "#6FA8C4"),
 ("collector","Tax collectors",           "#7E6E9B", "#A392C4"),
 ("critique", "Tithing rebuked",          "#6E8A5E", "#93B182"),
 ("hebrews",  "The Hebrews 7 argument",   "#9A8352", "#C2A86E"),
 ("giving",   "Treasury and alms",        "#4E8E7A", "#7FC0AC"),
 ("debt",     "Debt and its parables",    "#94707A", "#BE939D"),
 ("market",   "Money changers",           "#857A6A", "#A99B87"),
 ("interest", "Interest forbidden",       "#8E2F4E", "#C4708C"),
 ("release",  "Remission and jubilee",    "#3F8FA0", "#77C0CE"),
 ("entrusted","Money entrusted",          "#8A6E3F", "#C4A173"),
 ("wages",    "Wages withheld",           "#5A6390", "#8F98C4"),
 ("gleaning", "Gleaning and the field's edge", "#7E9152", "#AEC182"),
 ("purse",    "The common purse",         "#2F7D5E", "#62B48F"),
 ("price",    "Pricing a person",         "#C08A2E", "#E0B45E"),
]

nodes = list(csv.DictReader(open(a.nodes, encoding='utf-8')))
edges = list(csv.DictReader(open(a.edges, encoding='utf-8')))
known = {c[0] for c in CLUSTERS}
fail, warn = [], []

ids = [n['id'] for n in nodes]
for d, c in Counter(ids).items():
    if c > 1: fail.append(f'duplicate node id: {d}')
for n in nodes:
    if n['cluster'] not in known: fail.append(f"{n['id']}: unknown cluster {n['cluster']}")
idset = set(ids)
for e in edges:
    if e['source'] not in idset: fail.append(f"edge source missing: {e['source']}")
    if e['target'] not in idset: fail.append(f"edge target missing: {e['target']}")
    if e['kind'] not in ('lex','ref','con'): fail.append(f"bad kind: {e['kind']}")
    if e['warrant'] not in ('states','supports','spec'): fail.append(f"bad warrant: {e['warrant']}")
seen = set()
for e in edges:
    k = tuple(sorted((e['source'], e['target'])))
    if k in seen: fail.append(f'duplicate edge: {k[0]}–{k[1]}')
    seen.add(k)

if not a.no_verify:
    if not os.path.exists(a.index):
        sys.exit(f'{a.index} not found. Run nrsv_index.py, or pass --no-verify.')
    raw = {r['ref']: r['text'] for r in json.load(open(a.index))}
    index = set(raw)
    for n in nodes:
        if n['ref'] not in index:
            fail.append(f"{n['id']}: {n['ref']} does not resolve in the index")

    # A resolvable reference is not a correct one. This catches the case where a
    # summary describes a different verse than the one it cites: no content word
    # in common between the summary and the verse. It WARNS rather than fails,
    # because meta-summaries ("Mark's form of the ruling") legitimately share no
    # vocabulary with the text. Read the list; do not ignore it.
    import re as _re
    STOP = set("""the and for with that this from they them their there then than have has
    had was were will would shall should could been being into onto upon what which who whom
    whose when where while because before after over under again more most other some such
    only own same both each all any are but not you your his her its our out off down about
    against form account version repeated cited together""".split())
    _stem = lambda w: _re.sub(r'(ies|es|s)$', '', w)
    def _words(s):
        return {_stem(w) for w in _re.findall(r"[a-z']+", s.lower())
                if len(w) > 3 and w not in STOP}
    for n in nodes:
        t = raw.get(n['ref'])
        if t and not (_words(n['gist']) & _words(t)):
            warn.append(f"{n['id']} ({n['ref']}): summary shares no wording with the verse "
                        f"— check it names the right passage")

if fail:
    print('refusing to write:', file=sys.stderr)
    for f in fail: print('  ', f, file=sys.stderr)
    sys.exit(1)

j = lambda s: json.dumps(s, ensure_ascii=False)
out = ['// <corpus>  generated by build_graph.py — edit the CSVs, not this block']
out.append('const CL = {')
for k, name, lt, dk in CLUSTERS:
    out.append(f'  {k}:{{name:{j(name)},light:{j(lt)},dark:{j(dk)}}},')
out.append('};')
out.append('const N = [')
for n in nodes:
    out.append(f"  [{j(n['id'])},{j(n['ref'])},{j(n['cluster'])},{j(n['gist'])}],")
out.append('];')
out.append('const E = [')
for e in edges:
    out.append(f"  [{j(e['source'])},{j(e['target'])},{j(e['kind'])},{j(e['warrant'])},{j(e['note'])}],")
out.append('];')
out.append('// </corpus>')
block = '\n'.join(out)

html = open(a.graph, encoding='utf-8').read()
s, t = html.find('// <corpus>'), html.find('// </corpus>')
if s < 0 or t < 0:
    sys.exit('markers // <corpus> and // </corpus> not found in the graph file.')
html = html[:s] + block + html[t + len('// </corpus>'):]
open(a.graph, 'w', encoding='utf-8').write(html)

print(f'wrote {len(nodes)} nodes, {len(edges)} edges into {a.graph}')
if warn:
    print(f'\n{len(warn)} node(s) to check by eye:')
    for w in warn: print('  ', w)
print('clusters:', ', '.join(f'{k}={v}' for k, v in
      sorted(Counter(n["cluster"] for n in nodes).items(), key=lambda x: -x[1])))
